### ISSUE TITLE
Add a (prerelease) NuGet package

### ISSUE THREAD

**Issue by MihaMarkic** [vcsjones/OpenOpcSignTool#21]
It would be nice to have it distributed through a NuGet package, which can be marked as prerelease for the time being.

**Comment by vcsjones** [comment]
Yep. Working on it.

**Comment by ventsislav-georgiev** [comment]
It will be great to distribute the tool via nuget. Do you need help to publish it?

**Comment by vcsjones** [comment]
>It will be great to distribute the tool via nuget. Do you need help to publish it?

Ah, no I just haven't gotten to it. Thanks for reminding me. Are you primarily interested in consuming it as a library, or as an executable? For the latter, I was thinking about publishing it as a Chocolatey package as well as offical ZIPs in GitHub. For the former, a NuGet package would make the most sense to publish the Core library.

**Comment by ventsislav-georgiev** [comment]
I am more interested in using it as executable and I am fine in using Chocolatey, however, nuget integrates best in VS and it is easier for me to add an msbuild target for release builds to use the tool and sign the vsix package.

**Comment by jpmnteiro** [comment]
Any word on this? Looks like a great library, but need a way to distribute it to the build agents.

**Comment by vcsjones** [comment]
Sorry for the long wait.

* [OpenVsixSignTool][1] CLI is a nuget global tool.
* [OpenVsixSignTool.Core][1] library is available on NuGet.


[1]: https://www.nuget.org/packages/OpenVsixSignTool/
[2]: https://www.nuget.org/packages/OpenVsixSignTool.Core/
